In [17]:
import pandas as pd 

dataset1a = pd.read_csv('dataset1a.csv')
dataset1b = pd.read_csv('dataset1b.csv')
point = [[3],[3]]

from scipy.spatial.distance import cdist
import numpy
from sklearn.metrics.pairwise import euclidean_distances

import math

In [21]:
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances(dataset1a,[[3,3]])

array([[ 4.0358103 ],
       [ 1.61030422],
       [ 1.14145997],
       [ 2.21549133],
       [ 5.08353875],
       [ 4.70789929],
       [ 2.4275229 ],
       [ 8.3470494 ],
       [ 4.19844684],
       [ 4.70298385],
       [ 7.78595462],
       [ 9.5510538 ],
       [ 3.753344  ],
       [ 5.92600557],
       [ 3.9861214 ],
       [ 2.0903143 ],
       [ 4.82597701],
       [ 4.13578351],
       [ 1.80149135],
       [ 1.42577584],
       [ 7.97766427],
       [ 3.70294266],
       [ 3.5465506 ],
       [ 7.15184498],
       [ 4.87922047],
       [ 7.16854843],
       [ 6.83489787],
       [ 7.49530489],
       [ 5.36885489],
       [ 3.32738901],
       [ 5.93405273],
       [ 5.00498581],
       [ 7.90538965],
       [ 3.19912012],
       [ 4.0325878 ],
       [ 6.31465204],
       [ 2.78082891],
       [ 0.65497015],
       [ 3.75720333],
       [ 3.15538875],
       [ 5.61590149],
       [ 3.45288138],
       [ 2.91771759],
       [ 9.50929764],
       [ 1.8414534 ],
       [ 1

In [22]:
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances(dataset1b,[[3,3]])

array([[3.0182614 ],
       [1.54052803],
       [1.80937172],
       [0.9157057 ],
       [2.60997512],
       [2.03423608],
       [0.59228885],
       [0.20455555],
       [1.59689677],
       [2.79854421],
       [1.57239765],
       [0.35217223],
       [1.72855391],
       [2.99410354],
       [0.90952034],
       [2.54037043],
       [0.94082172],
       [0.40770383],
       [1.36727151],
       [2.49559254],
       [1.5303693 ],
       [1.80909531],
       [1.62754365],
       [2.35547399],
       [1.96161904],
       [1.7265214 ],
       [1.62967707],
       [2.22583   ],
       [1.34699422],
       [3.09669813],
       [4.09657542],
       [1.62169858],
       [0.14651595],
       [2.13213739],
       [2.67598026],
       [2.88027201],
       [1.81191774],
       [1.19757009],
       [1.80770358],
       [1.69872804],
       [2.95443516],
       [0.86833719],
       [0.35043714],
       [2.27798407],
       [0.50535902],
       [2.5422178 ],
       [1.45229865],
       [1.858

In [23]:
from sklearn.metrics.pairwise import manhattan_distances
manhattan_distances(dataset1a,[[3,3]])

array([[ 4.92965702],
       [ 2.09114178],
       [ 1.55639417],
       [ 2.42909695],
       [ 6.88119532],
       [ 5.7453398 ],
       [ 3.41447856],
       [11.68790844],
       [ 5.16081074],
       [ 4.92971901],
       [10.90186366],
       [13.47061338],
       [ 3.79413441],
       [ 6.85226793],
       [ 5.14997914],
       [ 2.57200262],
       [ 6.82421489],
       [ 5.803961  ],
       [ 2.54725819],
       [ 1.88663651],
       [ 9.65232781],
       [ 4.96412468],
       [ 4.98188276],
       [ 9.95214522],
       [ 6.19258382],
       [ 8.81337073],
       [ 8.01692312],
       [ 9.57829451],
       [ 6.95858283],
       [ 4.01064833],
       [ 8.38734016],
       [ 5.80359942],
       [11.0228495 ],
       [ 4.36575654],
       [ 5.65011459],
       [ 8.6523529 ],
       [ 3.56266235],
       [ 0.75704973],
       [ 4.84382831],
       [ 4.07677942],
       [ 7.27292674],
       [ 3.86843014],
       [ 3.30874164],
       [12.97043808],
       [ 2.44747803],
       [ 1

In [24]:
from sklearn.metrics.pairwise import manhattan_distances
manhattan_distances(dataset1b,[[3,3]])

array([[3.72777006],
       [2.06408399],
       [2.06822042],
       [1.29385676],
       [3.49942239],
       [2.49317697],
       [0.83262272],
       [0.23141056],
       [2.23143472],
       [3.95208448],
       [1.91676164],
       [0.45135327],
       [2.43886943],
       [4.17142971],
       [1.04465223],
       [3.57769818],
       [1.0130786 ],
       [0.55390892],
       [1.86743339],
       [2.67358877],
       [2.06529608],
       [1.9558349 ],
       [1.82735391],
       [3.13222795],
       [2.77139597],
       [2.44125191],
       [2.30465123],
       [2.85046691],
       [1.54424867],
       [3.35234622],
       [5.6802857 ],
       [1.99037969],
       [0.15306248],
       [2.85589727],
       [3.06845839],
       [3.19897506],
       [2.42949963],
       [1.37234961],
       [2.52777797],
       [1.92072432],
       [4.16835001],
       [1.22599122],
       [0.45534631],
       [3.21892574],
       [0.64553044],
       [3.41475456],
       [2.05344258],
       [2.511

In [39]:
from sklearn.neighbors import DistanceMetric
dist = DistanceMetric.get_metric('mahalanobis')
dist.metric_params='V'
dist.pairwise(dataset1a,[[3,3]])

ValueError: Must provide either V or VI for Mahalanobis distance

In [35]:
from sklearn.neighbors import DistanceMetric
dist = DistanceMetric.get_metric('mahalanobis')
dist.pairwise(dataset1b,[[3,3]])

ValueError: Must provide either V or VI for Mahalanobis distance